Create project. Create entities diagnoses and event. Cread CRUD all entities
trodriguez87/medicalApp pull request #2
Opened 2020-05-25 21:21 UTC by taniarodriguez

2020-06-13 22:11 UTC, EngAndres reviewed
Please, check it out, and resolve each one of the comments!

2020-06-13 22:11 UTC, EngAndres commented on 1589903015901-CreateEventTable.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
Include a header about software licence. I recommend to use GPL/GNU 3.0

2020-06-13 22:11 UTC, EngAndres commented on 1589903015901-CreateEventTable.ts
> +        await queryRunner.query(`CREATE TABLE "event" ("id" SERIAL NOT NULL,
Do not use SERIAL, please use UUID.

2020-06-13 22:11 UTC, EngAndres commented on ormconfig.json
> +  "database": "postgres",
setup a different database

2020-06-13 22:11 UTC, EngAndres commented on package.json
> +{
package-lock.json must be added to .gitignore.

2020-06-13 22:11 UTC, EngAndres commented on package.json
> +  "license": "UNLICENSED",
search licence, could be someone from either Apache or MIT

2020-06-13 22:11 UTC, EngAndres commented on package.json
> +    "migration:generate": "yarn run typeorm migration:generate -n",
remove run, they are not necessary
"yarn typeorm migration.."

2020-06-13 22:11 UTC, EngAndres commented on src/app.module.ts
> +  imports: [TypeOrmModule.forRoot(), EventModule, DiagnoseModule],
make a list going up2down. I mean, it is easy to see in a vertical distribution, not in a horizontal distribution

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    constructor(private readonly diagnoseServices:DiagnoseService){
remove spaces between brackets

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async getOne(@Param('idDiagnose') idDiagnose: string): Promise<Diagnose>{
IGNORE THIS ONE, IT IS A COMMENT FOR SERVICE FILE
what happens if this service can't find any object based on the constraint?

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async getOne(@Param('idDiagnose') idDiagnose: string): Promise<Diagnose>{
const diagnose: Diagnose = await this.diagnoseServices.findOne(idDiagnose)
if(!diagnose) {
     throw new NotFoundException()
}
return diagnose

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async update(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<any>{
Promise<Diagnose>

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async create (@Body() diagnosesData: Diagnose): Promise<any>{
Promise<Diagnose>

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async delete(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<any>{
Promise<Diagnose>

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +        return this.diagnoseServices.update(diagnoseData);
use SAVE

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +        diagnoseData.id = id;
const diagnose: Diagnose = await this.service.findOne(id)
diagnose.isActive = false
return this.diagnoseServices.save(diagnose)

2020-06-13 22:11 UTC, EngAndres commented on src/diagnose/diagnose.module.ts
> +  imports: [
order, imports first

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.controller.ts
> +    }*/
delete it!

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.controller.ts
> +
validate mandatory fields

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.controller.ts
> +
export async function checkParameterExistence(value: any) {
        if(value === null || !value || value === undefined) {
                throw new HttpException({
                statusCode: 400,
                error: 'Incorrect paremeter(s).',
                message: this.parameterExistenceError
            }, 400);
        }
    }

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.controller.ts
> +    async update (@Param('id') id: string, @Body() eventData: Event):Promise<any>{
apply same comments from Review Controller above

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.service.ts
> +    async findOne(idEvent: string): Promise<Event>{
add objects existence validation

2020-06-13 22:11 UTC, EngAndres commented on src/event/event.service.ts
> +    async update(event: Event): Promise<UpdateResult>{
delete it!

2020-06-13 22:11 UTC, EngAndres commented on src/main.ts
> +  const app = await NestFactory.create(AppModule);
enable CORS

2020-06-13 22:26 UTC, EngAndres requested changes
I just add two additional comments

2020-06-13 22:26 UTC, EngAndres commented on src/entities/event.entity.ts
> +    id: string;
@PrimaryGeneratedColumn('uuid')
 @IsOptional()
 @IsUUID()
  id?: string;

id must be in BaseEntity

2020-06-13 22:26 UTC, EngAndres commented on src/entities/event.entity.ts
> +    @Column({nullable: false})
@Column({type: 'varchar', length: 30, nullable:false})
  @IsDefined()
  @Length(2, 30)
  name: string;

 @Column({type: 'varchar', length: 100, nullable:true})
  @IsOptional()
  @Length(0, 100)
  preparation?: string;

2020-06-16 17:35 UTC, taniarodriguez commented on 1589903015901-CreateEventTable.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
Add header about license

2020-06-16 17:59 UTC, taniarodriguez commented on ormconfig.json
> +  "database": "postgres",
Created a new database and setup it

2020-06-16 18:07 UTC, taniarodriguez commented on package.json
> +{
The file was added to .gitignore

2020-06-16 18:12 UTC, taniarodriguez commented on package.json
> +    "migration:generate": "yarn run typeorm migration:generate -n",
Remove run for migrations comands

2020-06-16 18:30 UTC, taniarodriguez commented on package.json
> +  "license": "UNLICENSED",
Added license and author

2020-06-16 21:47 UTC, taniarodriguez commented on src/app.module.ts
> +  imports: [TypeOrmModule.forRoot(), EventModule, DiagnoseModule],
Converted to a list

2020-06-16 21:48 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +    constructor(private readonly diagnoseServices:DiagnoseService){
Done it

2020-06-16 22:01 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +    async update(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<any>{
Changed promise

2020-06-16 22:02 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +    async create (@Body() diagnosesData: Diagnose): Promise<any>{
Changed Promise

2020-06-16 22:02 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +    async delete(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<any>{
Changed Promise

2020-06-16 22:13 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +        return this.diagnoseServices.update(diagnoseData);
Done it

2020-06-16 22:13 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +        diagnoseData.id = id;
Done it

2020-06-16 22:14 UTC, taniarodriguez commented on src/diagnose/diagnose.module.ts
> +  imports: [
Changed order

2020-06-16 22:15 UTC, taniarodriguez commented on src/event/event.controller.ts
> +    }*/
Done it

2020-06-16 22:18 UTC, taniarodriguez commented on src/event/event.controller.ts
> +
Added this

2020-06-16 22:18 UTC, taniarodriguez commented on src/event/event.controller.ts
> +    async update (@Param('id') id: string, @Body() eventData: Event):Promise<any>{
Done it

2020-06-16 22:20 UTC, taniarodriguez commented on 1589903015901-CreateEventTable.ts
> +        await queryRunner.query(`CREATE TABLE "event" ("id" SERIAL NOT NULL,
Changed

2020-06-16 22:21 UTC, taniarodriguez commented on src/event/event.service.ts
> +    async findOne(idEvent: string): Promise<Event>{
Done it

2020-06-16 23:35 UTC, taniarodriguez commented on src/event/event.service.ts
> +    async update(event: Event): Promise<UpdateResult>{
Done it

2020-06-17 01:46 UTC, taniarodriguez commented on src/entities/event.entity.ts
> +    id: string;
Done it

2020-06-17 01:53 UTC, taniarodriguez commented on src/entities/event.entity.ts
> +    @Column({nullable: false})
Done it

2020-06-17 02:01 UTC, taniarodriguez commented on src/main.ts
> +  const app = await NestFactory.create(AppModule);
Added code for enable CORS

2020-06-19 16:46 UTC, EngAndres requested changes

2020-06-19 16:46 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +        async function checkParameterExistence(value: any) {
no no, put this one in a Utility file at the src root, create as interface, and called in all the files you need this function. Otherwise, you should to copy+paste this fragment in all your controllers.

2020-06-19 16:46 UTC, EngAndres commented on src/diagnose/diagnose.controller.ts
> +    async update(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<Diagnose>{
you must validate the mandatory fields.

2020-06-19 16:46 UTC, EngAndres commented on src/entities/diagnoses.entity.ts
> +    @IsUUID()
please, add @IsOptional() for this field, cos' when you create a new one object, this filed is not defined. So, avoid this kind of future issues.

2020-06-19 16:46 UTC, EngAndres commented on src/entities/event.entity.ts
> +    id: string;
add IsOptional

2020-06-19 16:46 UTC, EngAndres commented on src/event/event.controller.ts
> +import { get } from 'http';
please, be careful. This is no the get you must call, in the 19 line is the right "get"

2020-06-19 16:46 UTC, EngAndres commented on src/event/event.controller.ts
> +        async function checkParameterExistence(value: any) {
look, so many copy+paste

2020-06-19 16:46 UTC, EngAndres commented on tests/unit/event.controller.test.js
> +describe("el primer test ejecutado", () => {
names and all things, please in english

2020-06-20 19:19 UTC, taniarodriguez commented on src/entities/diagnoses.entity.ts
> +    @IsUUID()
Ok

2020-06-20 19:20 UTC, taniarodriguez commented on src/entities/event.entity.ts
> +    id: string;
Ok

2020-06-23 15:31 UTC, EngAndres requested changes

2020-06-23 15:31 UTC, EngAndres commented on src/utilitiesInterface.ts
> + export class utilitiesInterface {
this one must be an interface class, so you can used without any constructor. Not like an object.
The name of the class must be Utilities. So, when you need an utility, just make: Utilities.checkParamenter...... without create an object, just importing the class.

2020-06-23 15:31 UTC, EngAndres commented on src/event/event.controller.ts
> +        this.checkParameterExistence(eventData.name);
it isn't this, must be Utilities.check....

2020-06-23 15:31 UTC, EngAndres commented on src/utilitiesInterface.ts
> + export class utilitiesInterface {
https://www.tutorialsteacher.com/typescript/typescript-static

2020-06-24 00:15 UTC, taniarodriguez commented on src/diagnose/diagnose.controller.ts
> +    async update(@Param('id') id:string, @Body() diagnoseData: Diagnose): Promise<Diagnose>{
done it

2020-06-24 01:41 UTC, EngAndres approved these changes

2020-06-24 18:53 UTC, merged