MCM - 11
trodriguez87/medicalApp pull request #3
Opened 2020-05-29 17:49 UTC by taniarodriguez

Create entity medical center, create CRUD and create test to all entities

2020-06-29 04:54 UTC, EngAndres requested changes

2020-06-29 04:54 UTC, EngAndres commented on yarn.lock
> +nest@^0.1.6:
este archivo debería estar en tu .gitignore, y no ser actualizado mediante commits.

2020-06-29 04:54 UTC, EngAndres commented on src/entities/medicalCenter.entity.ts
> +    document: string;
document in medical center? are you sure this one is the right name?

2020-06-29 04:54 UTC, EngAndres commented on tests/unit/diagnoses/diagnoses.entity.test.ts
> +it('Field ID is undefined', async() =>{
Test with: id: null, id: undefined.
Just for a couple of fields.

2020-06-29 04:54 UTC, EngAndres commented on tests/unit/medicalCenter/medicalCenter.entity.test.ts
> +
remove this empty lines

2020-06-29 04:54 UTC, EngAndres commented on src/medical-center/medical-center.controller.ts
> +export class MedicalCenterController extends Utilities {
este "extends" no debería ser necesario, con el solo import debería bastar

2020-06-29 04:54 UTC, EngAndres commented on src/medical-center/medical-center.controller.ts
> +        Utilities.checkParameterExistence(medicalData.isActive);
this field must not be mandatory...when you create it, this field could have a default value as "true"

2020-06-29 04:54 UTC, EngAndres commented on src/medical-center/medical-center.controller.ts
> +        medicalData.id = id;
this is a mistake, you cannot update the id :O :O

2020-06-29 04:54 UTC, EngAndres commented on src/medical-center/medical-center.controller.ts
> +
remove these empty fields

2020-06-29 04:54 UTC, EngAndres commented on src/medical-center/medical-center.controller.ts
> +        medicalData.id = id;
@Put(':id')
    async update(@Param('id') id:string, @Body() medicalData: MedicalCenter): Promise<MedicalCenter>{
        const medical: MedicalCenter = await this.medicalServices.findOne(id);
        //not all fields fields can be updated, please, be more careful with that
        Utilities.checkParameterExistence(medicalData.address);
        Utilities.checkParameterExistence(medicalData.document);
        Utilities.checkParameterExistence(medicalData.name);
        Utilities.checkParameterExistence(medicalData.phone);
       //you better update the same object you get from DB
       medical.phone = medicalData.phone;
        return this.medicalServices.save(medicalData);
    }

2020-06-29 04:54 UTC, EngAndres commented on tests/unit/event/event.controller.test.ts
> +});
you need to add test for update and delete

2020-07-15 20:15 UTC, taniarodriguez commented on yarn.lock
> +nest@^0.1.6:
Done!

2020-07-15 20:18 UTC, taniarodriguez commented on src/entities/medicalCenter.entity.ts
> +    document: string;
Changed name to "numberDocument" and add field "typeDocument"

2020-07-15 20:21 UTC, taniarodriguez commented on tests/unit/medicalCenter/medicalCenter.entity.test.ts
> +
Done

2020-07-16 18:16 UTC, taniarodriguez commented on src/medical-center/medical-center.controller.ts
> +export class MedicalCenterController extends Utilities {
Done

2020-07-16 18:19 UTC, taniarodriguez commented on src/medical-center/medical-center.controller.ts
> +        Utilities.checkParameterExistence(medicalData.isActive);
Ok, changed it

2020-07-16 18:23 UTC, taniarodriguez commented on src/medical-center/medical-center.controller.ts
> +
Ok

2020-07-16 19:15 UTC, taniarodriguez commented on src/medical-center/medical-center.controller.ts
> +        medicalData.id = id;
Changed it!

2020-07-16 20:16 UTC, taniarodriguez commented on tests/unit/diagnoses/diagnoses.entity.test.ts
> +it('Field ID is undefined', async() =>{
Added tests for all required fields (empty, undefined, null)

2020-07-17 19:42 UTC, taniarodriguez commented on tests/unit/event/event.controller.test.ts
> +});
Add test for necessary fields

2020-07-20 07:38 UTC, EngAndres approved these changes
So good!

2020-07-20 16:33 UTC, merged