MCM-15: CRUD MedicalEntity
trodriguez87/medicalApp pull request #5
Opened 2020-07-29 20:57 UTC by taniarodriguez

CRUD MedicalEntity entity
Test for this entity

2020-08-02 21:53 UTC, EngAndres requested changes
Review comments and apply all changes you consider are necessary.

2020-08-02 21:53 UTC, EngAndres commented on src/entities/IPS.entity.ts
>      @PrimaryGeneratedColumn("uuid")
defined or optional?

2020-08-02 21:53 UTC, EngAndres commented on src/entities/IPS.entity.ts
>      @IsBoolean()
defined or optional?

2020-08-02 21:53 UTC, EngAndres commented on src/entities/IPS.entity.ts
> +    @IsDefined()
here this tag is unnecesary

2020-08-02 21:53 UTC, EngAndres commented on src/entities/medicalEntity.entity.ts
> +    @IsDefined()
this tag is unnecesary.

2020-08-03 16:00 UTC, taniarodriguez commented on src/entities/IPS.entity.ts
> +    @IsDefined()
Ok

2020-08-03 16:01 UTC, taniarodriguez commented on src/entities/medicalEntity.entity.ts
> +    @IsDefined()
Ok

2020-08-03 21:44 UTC, taniarodriguez commented on src/entities/IPS.entity.ts
>      @IsBoolean()
This field IsDefined.
 @Column ({nullable: false})
    @IsDefined()
    @IsBoolean()
    isActive: boolean;

When we create a new register, the field IsActive is set here
medicalData.isActive = true;
And when the register is updated, it check if the field exist
Utilities.checkParameterExistence(medicalData.isActive);

2020-08-03 21:44 UTC, taniarodriguez commented on src/entities/IPS.entity.ts
>      @PrimaryGeneratedColumn("uuid")
The field is Optional

@PrimaryGeneratedColumn("uuid")
    @IsUUID()
    @IsOptional()
    id: string;

2020-08-04 02:56 UTC, EngAndres commented on src/entities/IPS.entity.ts
>      @IsBoolean()
ok, it is right

2020-08-12 04:02 UTC, EngAndres approved these changes

2020-08-13 18:28 UTC, merged